language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL

before_script:
  - mkdir build; cd build; cmake ../

script:
  - make all
  - make test
  
branches:
  only:
    - master
    - travis-build

os:
  - linux
  - osx