macro (ac_define_google_namespace _GOOGNAMESPACE)
	if("${_GOOGNAMESPACE}" STREQUAL "")
		message(STATUS "using no namespace for product")
		set(GOOGLE_NAMESPACE "")
		set(_START_GOOGLE_NAMESPACE_ "")
		set(_END_GOOGLE_NAMESPACE_ "")
		set(ac_google_namespace "")
		set(ac_google_start_namespace "")
		set(ac_google_end_namespace "")
		set(ac_htmlparser_namespace "")
	else()
		message(STATUS "using namespace ${_GOOGNAMESPACE}")
		set(GOOGLE_NAMESPACE "${_GOOGNAMESPACE}")
		set(_START_GOOGLE_NAMESPACE_ "namespace ${_GOOGNAMESPACE} {")
		set(_END_GOOGLE_NAMESPACE_ "}")
		set(ac_google_namespace "${_GOOGNAMESPACE}")
		set(ac_google_start_namespace "namespace ${_GOOGNAMESPACE} {")
		set(ac_google_end_namespace "}")
		set(ac_htmlparser_namespace "${_GOOGNAMESPACE}")
	endif()
endmacro(ac_define_google_namespace)
